
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '9lC\x1c\r\x06\t\xdc\xa5I\xfd\xb62KfI'

_lr_action_items = {'$end':([3,10,12,16,25,33,],[0,-6,-1,-7,-8,-13,]),'RETURN':([41,],[46,]),'FUNC':([17,22,23,32,39,52,57,58,60,66,67,71,72,],[21,-25,21,-26,-27,55,55,-19,-21,-20,-22,-23,-24,]),'DOT':([8,9,20,59,],[14,-39,-40,14,]),'RPAREN':([38,40,42,45,54,65,69,],[43,44,-29,-30,-32,-38,-31,]),'SEMI':([8,9,20,64,65,70,],[15,-39,-40,71,-38,72,]),'DEFINE':([13,],[19,]),'FLPAREN':([37,40,42,45,51,54,65,69,],[41,41,-29,-30,41,-32,-38,-31,]),'COMMA':([42,45,54,65,69,],[51,51,51,-38,-31,]),'IMPORT':([1,4,6,7,11,15,],[5,-3,5,-2,-4,-5,]),'OUT':([41,],[50,]),'FUNCTION':([13,],[17,]),'END':([24,],[33,]),'AT':([4,6,10,11,12,15,16,17,18,19,22,23,25,26,27,28,32,33,34,39,61,68,],[-3,13,-6,-4,13,-5,-7,-10,24,-12,-25,-9,-8,-15,-11,-14,-26,-13,-16,-27,-18,-17,]),'LPAREN':([31,35,],[37,38,]),'IN':([41,],[47,]),'IN_OUT':([41,],[48,]),'FRPAREN':([46,47,48,49,50,],[-35,-33,-36,53,-34,]),'ID':([2,5,9,14,20,21,29,52,53,55,56,57,58,59,60,62,63,66,67,71,72,],[7,9,-39,20,-40,31,35,9,9,63,65,9,-19,-37,-21,65,70,-20,-22,-23,-24,]),'COMPONENT':([0,],[2,]),'INTERFACE':([19,26,28,34,61,68,],[29,-15,29,-16,-18,-17,]),'BRPAREN':([36,52,57,58,60,66,67,71,72,],[39,61,68,-19,-21,-20,-22,-23,-24,]),'BLPAREN':([30,43,44,],[36,52,-28,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'at_operater_statment':([13,],[18,]),'at_statment':([6,12,],[10,16,]),'at_end_statment':([18,],[25,]),'statment':([0,],[3,]),'function_statment':([17,23,],[22,32,]),'interface_declare_statments':([52,],[57,]),'type_specifier':([52,53,57,],[56,62,56,]),'function_para':([37,40,51,],[42,45,54,]),'function_paras':([37,],[40,]),'interface_statments':([19,],[28,]),'function_statments':([17,],[23,]),'function_para_action':([41,],[49,]),'component_statment':([0,],[1,]),'import_statement':([1,6,],[4,11,]),'qualified_name':([5,52,53,57,],[8,59,59,59,]),'field_declare':([52,57,],[58,66,]),'function_declare':([52,57,],[60,67,]),'import_statements':([1,],[6,]),'interface_statment':([19,28,],[26,34,]),'declarator_name':([56,62,],[64,69,]),'at_statments':([6,],[12,]),'function_declarator':([21,],[30,]),'define_statments':([19,],[27,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('statment',3,'p_statment','./src/breed_yacc.py',20),
  ('component_statment',2,'p_component_statment','./src/breed_yacc.py',27),
  ('import_statements',1,'p_import_statements','./src/breed_yacc.py',33),
  ('import_statements',2,'p_import_statements','./src/breed_yacc.py',34),
  ('import_statement',3,'p_import_statement','./src/breed_yacc.py',39),
  ('at_statments',1,'p_at_statments','./src/breed_yacc.py',48),
  ('at_statments',2,'p_at_statments','./src/breed_yacc.py',49),
  ('at_statment',3,'p_at_statment','./src/breed_yacc.py',55),
  ('at_operater_statment',2,'p_at_operater_statment','./src/breed_yacc.py',60),
  ('at_operater_statment',1,'p_at_operater_statment','./src/breed_yacc.py',61),
  ('at_operater_statment',2,'p_at_operater_statment','./src/breed_yacc.py',62),
  ('at_operater_statment',1,'p_at_operater_statment','./src/breed_yacc.py',63),
  ('at_end_statment',2,'p_at_end_statment','./src/breed_yacc.py',68),
  ('define_statments',1,'p_define_statments','./src/breed_yacc.py',73),
  ('interface_statments',1,'p_interface_statments','./src/breed_yacc.py',79),
  ('interface_statments',2,'p_interface_statments','./src/breed_yacc.py',80),
  ('interface_statment',7,'p_interface_statment','./src/breed_yacc.py',86),
  ('interface_statment',6,'p_interface_statment','./src/breed_yacc.py',87),
  ('interface_declare_statments',1,'p_interface_declare_statments','./src/breed_yacc.py',94),
  ('interface_declare_statments',2,'p_interface_declare_statments','./src/breed_yacc.py',95),
  ('interface_declare_statments',1,'p_interface_declare_statments','./src/breed_yacc.py',96),
  ('interface_declare_statments',2,'p_interface_declare_statments','./src/breed_yacc.py',97),
  ('field_declare',3,'p_field_declare','./src/breed_yacc.py',103),
  ('function_declare',4,'p_function_declare','./src/breed_yacc.py',108),
  ('function_statments',1,'p_function_statments','./src/breed_yacc.py',114),
  ('function_statments',2,'p_function_statments','./src/breed_yacc.py',115),
  ('function_statment',4,'p_function_statment','./src/breed_yacc.py',120),
  ('function_declarator',4,'p_function_declarator','./src/breed_yacc.py',127),
  ('function_paras',1,'p_function_paras','./src/breed_yacc.py',134),
  ('function_paras',2,'p_function_paras','./src/breed_yacc.py',135),
  ('function_para',5,'p_function_para','./src/breed_yacc.py',141),
  ('function_para',3,'p_function_para','./src/breed_yacc.py',142),
  ('function_para_action',1,'p_function_para_action','./src/breed_yacc.py',148),
  ('function_para_action',1,'p_function_para_action','./src/breed_yacc.py',149),
  ('function_para_action',1,'p_function_para_action','./src/breed_yacc.py',150),
  ('function_para_action',1,'p_function_para_action','./src/breed_yacc.py',151),
  ('type_specifier',1,'p_type_specifier','./src/breed_yacc.py',158),
  ('declarator_name',1,'p_declarator_name','./src/breed_yacc.py',164),
  ('qualified_name',1,'p_qualified_name','./src/breed_yacc.py',169),
  ('qualified_name',3,'p_qualified_name','./src/breed_yacc.py',170),
  ('empty',0,'p_empty','./src/breed_yacc.py',183),
]
