python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/hibernate3/BussinessEntity.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/hibernate3/HibernateDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/hibernate3/IdEntity.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/hibernate3/PropertyFilter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/hibernate3/SimpleHibernateDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/jdbc/JdbcDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/mybatis/DiclectResultSetHandlerInterceptor.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/mybatis/DiclectStatementHandlerInterceptor.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/mybatis/SQLiteDialect.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/support/Page.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/support/PageOption.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/dao/support/SQLiteDialect.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/json/JsonDateSerializer.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/spring/BaseController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/spring/ItecDxhxContextLoaderListener.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/spring/MappingJacksonHttpMessageConverter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/spring/MessageProvider.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/spring/ResourceBundleMessageSource.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/spring/SpringContext.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/APL_STATICS_CONST.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/BaseUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/BeanUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/CANNEL_CONSTANT.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/ColumnTypeMapperUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/EncodeUtils.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/Encode.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelBlackRow.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelColumn.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelColumnRow.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelLastLineRow.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelLineRow.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelMutRow.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelRow.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelRowLine.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelStyle.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelTitleRow.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/ExcelUtils.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/excel/reader/ExcelReader.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/ExportExcelUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/MD5.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/ModelValidator.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/NumberUtils.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/PropertiesUtils.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/ReflectionUtils.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/TimeUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/UUIDGenerator.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/utils/webServiceClient.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/common/xml/XtreamDateConverter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/AbstractClient.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/AbstractProcessor.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/AbstractServer.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/newpolicybean/MainErrorMsgBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/newpolicybean/request/NewPolicyRequestBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/newpolicybean/response/NewPolicyErrorResponseBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/newpolicybean/response/NewPolicyResponseBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/revokebean/request/RequestMainInfoBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/revokebean/request/RevokeRequestBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/revokebean/response/RevokeResponseBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/revokebean/ResponseMainInfoBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/trialbean/MainErrorMsgBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/trialbean/request/TrialRequestBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/trialbean/response/TrialErrorResponseBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/trialbean/response/TrialResponseBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/BbrOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/BbrTellerOfBeans.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/DetailList.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/HealthNoticeOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/MainOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/ProductOfBeans.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/PtOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/RMainOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/SpecContentOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/subbean/BbrTellerOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/subbean/DetailOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/subbean/ProductOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/subbean/sub2bean/ConiOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/subbean/sub2bean/VtiOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/subbean/SyrOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/subbean/TbrTellerOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/subbean/VtOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/SyrOfBeans.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/TbrOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/beans/unitybean/TbrTellerOfBeans.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/IBusinessTotalEntry.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/impl/BusinessTotalEntryImpl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/CError.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/CErrors.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/ChgData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/CloseIOStream.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/ConfigInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/Schema.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/SSRS.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/StrTool.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/SysConst.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/Tools.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/UserLog.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/VData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/utility/XmlOperator.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/validation/IInputDataValidation.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/validation/impl/InputDataValidationImpl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/xbt/XbtNewPolicy.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/xbt/XbtPremiumTrial.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/businessprocess/xbt/XbtRevokeOfDay.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/constant/InterConstants.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/exception/BusinessLogicException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/exception/CallSysInterfaceException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/exception/DataValidationException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/exception/InterfaceBeanConversionCorePojoException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/SocketRW.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/socketServerHandler.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/socketServerImpl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/hnnx/TransLog.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/newpolicybean/MainErrorMsgBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/newpolicybean/request/NewPolicyRequestBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/newpolicybean/response/NewPolicyErrorResponseBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/newpolicybean/response/NewPolicyResponseBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/revokebean/request/RequestMainInfoBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/revokebean/request/RevokeRequestBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/revokebean/response/RevokeResponseBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/revokebean/ResponseMainInfoBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/trialbean/MainErrorMsgBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/trialbean/request/TrialRequestBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/trialbean/response/TrialErrorResponseBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/trialbean/response/TrialResponseBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/BbrOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/BbrTellerOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/DetailList.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/HealthNoticeOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/MainOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/ProductOfBeans.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/PtOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/SpecContentOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/subbean/DetailOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/subbean/ProductOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/subbean/sub2bean/ConiOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/subbean/sub2bean/VtiOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/subbean/SyrOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/subbean/VtOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/SyrOfBeans.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/TbrOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/beans/unitybean/TbrTellerOfBean.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/IBusinessTotalEntry.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/impl/BusinessTotalEntryImpl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/CError.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/CErrors.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/ChgData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/CloseIOStream.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/ConfigInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/Schema.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/SSRS.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/StrTool.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/SysConst.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/Tools.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/UserLog.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/VData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/utility/XmlOperator.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/validation/IInputDataValidation.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/validation/impl/InputDataValidationImpl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/xbt/XbtNewPolicy.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/xbt/XbtPremiumTrial.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/businessprocess/xbt/XbtRevokeOfDay.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/constant/InterConstants.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/exception/BusinessLogicException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/exception/CallSysInterfaceException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/exception/DataValidationException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/exception/InterfaceBeanConversionCorePojoException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/QDsocketServerHandler.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/qdnx/QDsocketServerImpl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/util/converter/DateConverter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/servybt/util/XmlAnnotationTool.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/annotation/ParamTextAnnotation.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/annotation/processor/AnnotationProcessor.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/annotation/processor/ParamTextProcessor.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bl/common/DateJsonValueProcessor.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bl/common/exception/BusinessException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bl/common/exception/ErrorCodeConstant.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bl/common/exception/SystemException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bl/common/MD5.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bl/common/TreeObj.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/CustInfoBo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/DyParaValues.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/edor/EdorInfoBo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/edor/ProposalBo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/edor/RepealBo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/edor/TaskEInfoBo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/edor/TrackBo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/edor/WorkflowDriveBo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/KeyValueBo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/SpecDayBo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/bo/sys/MenuTree.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/constant/AgentConstant.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/constant/AgentCredentialAwardConstant.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/constant/edor/MappingKeys.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/constant/ExceptionCodeConstant.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/constant/OccupationCodeConstant.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/constant/OrganizationConstant.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/constant/ProductRunningConstant.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/agent/AgentCredentialAwardDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/agent/AgentDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/agent/AgentProductDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/agent/AgentStateHistoryDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/CertNoChangeDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/DayCannelPolDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/DayEfftPolDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/DayEfftPolReptDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/ExtraParaDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/InPayInfoExportDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/InPolQueryDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/ISCBrrDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/ISCOverseasRescueDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/ISCPublicTransAccDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/ISCStudentSecurityDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/ISCTransAccDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/MonthSaleReptDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/PolPrintDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/PolStatDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/PolStateQueryDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/PremDtlReptDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/PremSmmReptDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/PrintOptnDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/as/XmlAplDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/authority/RoleDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/authority/SysFunctionDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/authority/SysModuleDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/common/DataDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/common/GTDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/common/OccupationDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/customer/CustInfoDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/customer/CustInfoHistoryDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/customer/CustRelationShipDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/customer/CustSpecialDayDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/ApproveSelectDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/BeneficiaryChgDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/BeneficiaryChgDetailDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/DriveSelectDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/EdorDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/EdorDaoUtils.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/EdorItemDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/EdorNoDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/EdorPrintDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/EdorSelectDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/EndorsementDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/InsuredBaseInfoChgDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/InsuredMajorInfoChgDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/OccupationChgDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/RepealSelectDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/SurrenderDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/SurrenderKindDetailDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/edor/TaskTrackDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/expense/PaymentDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/gt/GtDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/gt/GtFactorDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/gt/GtPriceDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/gt/RateCancelDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurance/CoverageDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurance/InsurancedefineCoverageDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurance/InsuranceDefineDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurance/InsurancedefineRelationDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurance/ProtectPlanDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurancedef/ClaimDutyDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurancedef/DutyDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurancedef/InsPlanDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurancedef/InsPlanFactorDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurancedef/InsPlanRelationDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurancedef/InsuranceDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/insurancedef/PlanAuditDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/CustBaseDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/EdrAddressDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/EdrAplDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/EdrBnfDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/EdrCustBaseDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/EdrIsdDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/EdrPlcBaseDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/EdrPrdDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/InsuranceSlipSignDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/NbAddressDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/NbAplDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/NbBnfDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/NbIsdDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/NbLbtDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/NbPlcBaseDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/NbPlcCancelDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/NbPrdDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/NbSubLbtDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/nb/NbUWMainDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/organization/OrganizationDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/organization/ProductRunningDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/parameter/AttributeDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/parameter/ParameterDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/salesystem/GroupInsHibernateDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/salesystem/LaComDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/salesystem/LdComDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/salesystem/ScanSystemHibernateDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/salesystem/SisLaComDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/sys/JobDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/sys/LogDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/dao/user/UserDao.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/exception/StisException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/exception/ValidException.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/export/as/CertExportExcel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/export/as/DayCannelExportExcel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/export/as/DayEfftPolExport.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/export/as/MonthSaleReptExport.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/export/as/PayInfoExportExcel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/export/as/PolQueryExportExcel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/export/as/PolStateQueryExportExcel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/export/as/PolStatExport.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/export/as/PremDtlReptExport.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/export/as/PremSmmReptExport.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/agent/Agent.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/agent/AgentCredentialAward.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/agent/AgentProduct.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/agent/AgentStateHistory.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INAddress.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INApl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INBaseInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INBndInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INBnf.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INBnfInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INInputData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INIsd.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INLbt.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INOUTXmlApl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INPlcBase.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INPrd.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INPrdInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/aplxmlmodel/INTransData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/cancelxmlmodel/INBaseInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/cancelxmlmodel/INInputData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/cancelxmlmodel/INTransData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/cancelxmlmodel/OUTRetData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/cancelxmlmodel/OUTTranData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/ExtraPara.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INCertNoChange.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INChangePWD.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INDayCannelPol.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INDayEfftPol.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INElcPolQuery.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INISCBrrPersonAccJury.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INISCCommon.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INISCFlightAcc.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INISCOverseasRescue.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INISCPublicTransAcc.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INISCStudentSecurity.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INISCTransAcc.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INMonthSaleRept.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INPayInfoExport.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INPolPrint.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INPolQuery.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INPolStat.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INPolStateQuery.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/INPremRept.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTAplSubmitResult.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTCertNoChange.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTDayCannelPol.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTDayEfftPol.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTElcPolQuery.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTMonthSaleRept.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTPayInfoExport.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTPolPrint.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTPolQuery.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTPolStat.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTPolStateQuery.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTPremRept.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/OUTPrintPlgn.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/Person.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/as/PrintOptn.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/authority/Role.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/authority/RoleModuleFuncRel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/authority/SysFunction.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/authority/SysModule.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/authority/SysModuleNew.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/authority/UserFunctionRel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/authority/UserRoleRel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/common/BasePojo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/common/FactorType.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/common/GTColumn.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/common/GTDataStructure.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/common/GTTableStructure.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/customer/CustInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/customer/CustInfoHistory.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/customer/RelationShip.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/customer/SpecialDays.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/BeneficiaryChg.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/BeneficiaryChgDetail.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/EdorItem.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/EdorNo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/EdorTasks.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/Endorsement.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/InsuredBaseInfoChg.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/InsuredMajorInfoChg.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/OccupationChg.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/Surrender.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/SurrenderKindDetail.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edor/TaskTrack.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrAddress.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrAddressPK.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrApl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrBnf.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrCustBase.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrIformation.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrIsd.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrLbt.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrPlcBase.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrPlcCancel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrPrd.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrPrmDtl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrSubLbt.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrUWDetail.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/EdrUWMain.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/edr/SaveEdrVO.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/expense/Payment.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/expense/PaymentDetail.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/gt/Gt.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/gt/GtFactor.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/gt/RateCancel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurance/Coverage.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurance/InsuranceAttr.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurance/InsuranceDefine.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurance/InsurancedefineCoverage.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurance/InsurancedefineRelation.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurance/ProtectInsuranceDefine.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurance/ProtectPlan.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurancedef/ClaimDuty.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurancedef/Duty.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurancedef/InsPlan.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurancedef/InsPlanFactor.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurancedef/InsPlanRelation.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurancedef/Insurance.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/insurancedef/PlanAudit.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/CustBase.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/InsuranceSlipSignVO.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbAddress.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbAddressPK.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbApl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbBnf.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbIformation.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbIsd.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbLbt.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbPlcBase.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbPlcCancel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbPrd.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbPrmDtl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbSubLbt.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbUWDetail.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/NbUWMain.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/QueryNbPlcBaseVO.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/RevokeDisposeVO.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/nb/UnderwritingStopVO.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/organization/Organization.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/organization/ProductRunning.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/parameter/Attribute.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/parameter/AttributeValue.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/parameter/ParaCache.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/parameter/Parameter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/parameter/ParameterValue.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/protect/Occupations.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/protect/PartyDef.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/salesystem/LaCom.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/salesystem/LdCom.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/salesystem/SisLaCom.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/StisModel.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/sys/JobDefine.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/sys/JobLog.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/sys/JobResult.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/sys/Log.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/model/user/User.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/ConstCancelType.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/DefinePremiumCalcService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/EndorseRuleResult.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/LbtCheckUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/Message.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/PremiumCalcService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/ProposalRuleResult.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/RuleCheckStatus.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/RuleConstant.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/RuleEngine.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/RuleEngineInitUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/RuleUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/xmlvo/Check.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/xmlvo/CheckRules.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/xmlvo/GroupType.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/rule/xmlvo/RuleType.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/agent/AgentCredentialAwardService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/agent/AgentProductService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/agent/AgentService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/agent/AgentStateHistoryService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/annotation/ParamTextService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/asUtils.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/CertNoChangeService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/DayCannelPolService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/DayEfftPolReptService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/ExtraParaService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/InPayInfoExportService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/InPolQueryService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/ISCBrrService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/ISCFlightAccService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/ISCOverseasRescueService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/ISCPublicTransAccService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/ISCStudentSecurityService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/ISCTransAccService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/MonthSaleReptService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/PolPrintService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/PolStateQueryService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/PolStatService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/PremDtlReptService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/PremSmmReptService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/PrintOptnService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/PrintPlgnService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/as/xmlUtils.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/authority/RoleService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/authority/SysModuleService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/authority/UserDetailServiceImpl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/cache/CacheService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/cache/ParaCacheManager.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/common/BatchJobTask.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/common/DataService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/common/GTService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/common/OccupationService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/customer/CustInfoService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/edor/EdorItemCompare.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/edor/EdorProposalService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/edor/EdorService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/edor/EdorUtils.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/edor/TrackService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/expense/PaymentService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/gt/GtPriceService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/gt/GtService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/gt/RateCancelService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/insurance/CoverageService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/insurance/InsuranceDefineService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/insurance/ProtectPlanService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/insurancedef/ClaimDutyService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/insurancedef/DutyService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/insurancedef/InsPlanFactorService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/insurancedef/InsPlanRelationService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/insurancedef/InsPlanService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/insurancedef/InsuranceService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/insurancedef/PlanAuditService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/nb/AutoUWService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/nb/CalProposalPreService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/nb/GenerateSN.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/nb/InsuranceSlipSignService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/nb/NbPlcBaseService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/nb/NbPlcCancelService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/nb/NbUWMainService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/organization/OrganizationService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/organization/ProductRunningService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/parameter/AttributeService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/parameter/ParameterService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/salesystem/SaleSystemService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/sys/JobService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/sys/LogService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/sys/MenuService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/service/user/UserService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/as/AgentSaleController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/as/DayCannelPolController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/as/InPayInfoExportController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/as/InPolQueryController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/as/PolStateQueryController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/authority/RoleController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/authority/SysModuleController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/cust/CustController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/edor/EdorController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/gt/GtController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/gt/RateCancelController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/insurancedef/ProductDefController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/job/BatchJobTask.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/job/CustInfoBatchJobTask.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/job/JobController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/MainController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/MessageResource.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/nb/InsuranceSlipSignController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/nb/ProposalInputController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/nb/RevokeDisposeController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/nb/UnderwritingStopController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/organization/OrganizationController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/parameter/ParameterController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/system/LogController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/system/LoginController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/system/OccupationController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/controller/user/UserController.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/filter/CheckLoginFilter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/tag/ParamTag.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/utils/ControllerUtils.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/web/utils/UserUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/DataServiceImpl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/edor/EndorTaskService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/edor/EndorTaskServiceImpl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/IDataService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/converter/DateConverter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/converter/DoubleConverter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/converter/InsuranceConverter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/converter/IntConverter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/converter/LongConverter.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/INbDataService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/NbDataServiceImpl.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/BaseInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/BonusValuesRet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/CashValueRet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/CashValuesRet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/InputData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/NbAplRet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/NbBnfInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/NbBnfInfoRet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/NbBnfRet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/NbIsdRet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/NbLbtRet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/NbPlcBaseRet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/NbPOJO.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/NbPOJORet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/NbPrdRet.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/PrdInfo.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/nb/pojo/RetData.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/ReturnMsg.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/StisWebService.java
python main.py --file  /Users/zhaonf/program/insurance/src/main/java/com/itec/stis/webservice/util/XMLAnnotationUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/test/com/itec/stis/test/BaseTestUnit.java
python main.py --file  /Users/zhaonf/program/insurance/src/test/com/itec/stis/test/cust/CustServiceTest.java
python main.py --file  /Users/zhaonf/program/insurance/src/test/com/itec/stis/test/expense/PaymentServiceTest.java
python main.py --file  /Users/zhaonf/program/insurance/src/test/com/itec/stis/test/HibernateUtil.java
python main.py --file  /Users/zhaonf/program/insurance/src/test/com/itec/stis/test/JeffUserTest.java
python main.py --file  /Users/zhaonf/program/insurance/src/test/com/itec/stis/test/log/LogServiceTest.java
python main.py --file  /Users/zhaonf/program/insurance/src/test/com/itec/stis/test/RuleEngineTest.java
python main.py --file  /Users/zhaonf/program/insurance/src/test/com/itec/stis/test/Test.java
python main.py --file  /Users/zhaonf/program/insurance/src/test/com/itec/stis/test/webservice/edor/EndorTaskServiceTest.java
python main.py --file  /Users/zhaonf/program/insurance/src/test/com/itec/stis/test/webservice/WebserviceBaseTestUnit.java
