
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\x9d@\x90\xb9\xdd\x9dr\xfbm0\xc23\x85\xd3E}'

_lr_action_items = {'GRAMMAR':([0,],[1,]),'SPE_TOKEN':([13,17,18,19,20,21,22,23,24,25,26,31,32,33,34,35,36,37,38,39,40,41,43,44,46,],[26,-16,-17,26,-12,26,26,-25,-29,-15,-30,26,-24,-28,-26,26,-21,-27,26,-13,-23,26,-14,-18,-19,]),'SEMI':([4,13,17,18,19,20,21,23,24,25,26,31,32,33,34,36,37,38,39,40,42,43,44,46,],[7,-20,-16,-17,30,-12,-10,-25,-29,-15,-30,-11,-24,-28,-26,-21,-27,-20,-13,-23,45,-14,-18,-19,]),'RPAREN':([17,18,20,22,23,24,25,26,32,33,34,35,36,37,38,39,40,41,43,44,46,],[-16,-17,-12,40,-25,-29,-15,-30,-24,-28,-26,-20,-21,-27,-20,-13,-23,44,-14,-18,-19,]),'EQUALS':([15,],[27,]),'BLPAREN':([6,],[11,]),'VERTICAL':([13,17,18,19,20,21,22,23,24,25,26,31,32,33,34,35,36,37,38,39,40,41,43,44,46,],[-20,-16,-17,-20,-12,38,-20,-25,-29,-15,-30,38,-24,-28,-26,-20,-21,-27,-20,-13,-23,38,-14,-18,-19,]),'QUES':([13,17,18,19,20,21,22,23,24,25,26,31,32,33,34,35,36,37,38,39,40,41,43,44,46,],[-20,-16,-17,-20,33,-10,-20,-25,-29,-15,-30,-11,-24,-28,-26,-20,-21,-27,-20,33,-23,-20,33,33,-19,]),'COLON':([10,],[13,]),'LPAREN':([13,17,18,19,20,21,22,23,24,25,26,31,32,33,34,35,36,37,38,39,40,41,43,44,46,],[22,-16,-17,22,35,22,22,-25,-29,-15,-30,22,-24,-28,-26,22,-21,-27,22,35,-23,22,35,-18,-19,]),'PLUS':([13,17,18,19,20,21,22,23,24,25,26,31,32,33,34,35,36,37,38,39,40,41,43,44,46,],[-20,-16,-17,-20,34,-10,-20,-25,-29,-15,-30,-11,-24,-28,-26,-20,-21,-27,-20,34,-23,-20,34,34,-19,]),'ID':([1,5,8,9,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,43,44,45,46,],[4,10,10,-7,15,-8,24,-4,15,-16,-17,24,-12,24,24,-25,-29,-15,-30,42,-3,-5,-9,24,-24,-28,-26,24,-21,-27,24,-13,-23,24,-14,-18,-6,-19,]),'BRPAREN':([14,16,29,45,],[-4,28,-5,-6,]),'OPTIONS':([3,7,],[6,-2,]),'MULT':([13,17,18,19,20,21,22,23,24,25,26,31,32,33,34,35,36,37,38,39,40,41,43,44,46,],[-20,-16,-17,-20,37,-10,-20,-25,-29,-15,-30,-11,-24,-28,-26,-20,-21,-27,-20,37,-23,-20,37,37,-19,]),'$end':([2,8,9,12,30,],[0,-1,-7,-8,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'s_expr':([13,19,21,22,31,35,38,41,],[18,18,18,18,18,18,18,18,]),'options_statment':([3,],[5,]),'grammar_statment':([0,],[3,]),'ptoken':([13,19,21,22,31,35,38,41,],[17,17,17,17,17,17,17,17,]),'rules':([13,],[19,]),'expr':([13,19,21,22,31,35,38,41,],[20,20,39,20,39,20,43,39,]),'rule_statments':([5,],[8,]),'rule':([13,19,22,35,],[21,31,41,41,]),'program':([0,],[2,]),'rule_statment':([5,8,],[9,12,]),'operator':([20,39,43,44,],[36,36,36,46,]),'sub_expr':([13,19,20,21,22,31,35,38,39,41,43,],[23,23,32,23,23,23,23,23,32,23,32,]),'option_statment':([11,16,],[14,29,]),'empty':([13,19,22,35,],[25,25,25,25,]),'option_statments':([11,],[16,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('program',3,'p_program','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',76),
  ('grammar_statment',3,'p_grammar_statment','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',82),
  ('options_statment',4,'p_options_statment','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',88),
  ('option_statments',1,'p_option_statments','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',94),
  ('option_statments',2,'p_option_statments','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',95),
  ('option_statment',4,'p_option_statment','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',101),
  ('rule_statments',1,'p_rule_statments','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',107),
  ('rule_statments',2,'p_rule_statments','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',108),
  ('rule_statment',4,'p_rule_statment','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',113),
  ('rules',1,'p_rules','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',125),
  ('rules',2,'p_rules','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',126),
  ('rule',1,'p_rule','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',135),
  ('rule',2,'p_rule','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',136),
  ('rule',3,'p_rule','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',137),
  ('rule',1,'p_rule','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',138),
  ('expr',1,'p_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',149),
  ('expr',1,'p_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',150),
  ('sub_expr',3,'p_sub_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',157),
  ('sub_expr',4,'p_sub_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',158),
  ('s_expr',0,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',171),
  ('s_expr',2,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',172),
  ('s_expr',1,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',173),
  ('s_expr',2,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',174),
  ('s_expr',2,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',175),
  ('s_expr',1,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',176),
  ('operator',1,'p_operator','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',190),
  ('operator',1,'p_operator','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',191),
  ('operator',1,'p_operator','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',192),
  ('ptoken',1,'p_ptoken','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',198),
  ('ptoken',1,'p_ptoken','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',199),
  ('empty',0,'p_empty','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',207),
]
