
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xd0\xb1\xc0S\x03\xf0\x9f1U\x05N\xfd\x0f\rS,'
    
_lr_action_items = {'GRAMMAR':([0,],[1,]),'SPE_TOKEN':([14,18,19,20,21,22,23,24,25,26,27,32,33,34,35,36,37,38,39,40,41,42,44,45,47,],[27,-17,-18,27,-13,27,27,-26,-30,-16,-31,27,-25,-29,-27,27,-22,-28,27,-14,-24,27,-15,-19,-20,]),'SEMI':([4,14,18,19,20,21,22,24,25,26,27,32,33,34,35,37,38,39,40,41,43,44,45,47,],[8,-21,-17,-18,31,-13,-11,-26,-30,-16,-31,-12,-25,-29,-27,-22,-28,-21,-14,-24,46,-15,-19,-20,]),'RPAREN':([18,19,21,23,24,25,26,27,33,34,35,36,37,38,39,40,41,42,44,45,47,],[-17,-18,-13,41,-26,-30,-16,-31,-25,-29,-27,-21,-22,-28,-21,-14,-24,45,-15,-19,-20,]),'EQUALS':([16,],[28,]),'BLPAREN':([6,],[12,]),'VERTICAL':([14,18,19,20,21,22,23,24,25,26,27,32,33,34,35,36,37,38,39,40,41,42,44,45,47,],[-21,-17,-18,-21,-13,39,-21,-26,-30,-16,-31,39,-25,-29,-27,-21,-22,-28,-21,-14,-24,39,-15,-19,-20,]),'QUES':([14,18,19,20,21,22,23,24,25,26,27,32,33,34,35,36,37,38,39,40,41,42,44,45,47,],[-21,-17,-18,-21,34,-11,-21,-26,-30,-16,-31,-12,-25,-29,-27,-21,-22,-28,-21,34,-24,-21,34,34,-20,]),'COLON':([11,],[14,]),'LPAREN':([14,18,19,20,21,22,23,24,25,26,27,32,33,34,35,36,37,38,39,40,41,42,44,45,47,],[23,-17,-18,23,36,23,23,-26,-30,-16,-31,23,-25,-29,-27,23,-22,-28,23,36,-24,23,36,-19,-20,]),'PLUS':([14,18,19,20,21,22,23,24,25,26,27,32,33,34,35,36,37,38,39,40,41,42,44,45,47,],[-21,-17,-18,-21,35,-11,-21,-26,-30,-16,-31,-12,-25,-29,-27,-21,-22,-28,-21,35,-24,-21,35,35,-20,]),'ID':([1,3,5,7,8,9,10,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,],[4,-32,11,-4,-2,11,-8,16,-9,25,-5,16,-17,-18,25,-13,25,25,-26,-30,-16,-31,43,-3,-6,-10,25,-25,-29,-27,25,-22,-28,25,-14,-24,25,-15,-19,-7,-20,]),'BRPAREN':([15,17,30,46,],[-5,29,-6,-7,]),'OPTIONS':([3,8,],[6,-2,]),'MULT':([14,18,19,20,21,22,23,24,25,26,27,32,33,34,35,36,37,38,39,40,41,42,44,45,47,],[-21,-17,-18,-21,38,-11,-21,-26,-30,-16,-31,-12,-25,-29,-27,-21,-22,-28,-21,38,-24,-21,38,38,-20,]),'$end':([2,9,10,13,31,],[0,-1,-8,-9,-10,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'s_expr':([14,20,22,23,32,36,39,42,],[19,19,19,19,19,19,19,19,]),'option_statment':([12,17,],[15,30,]),'grammar_statment':([0,],[3,]),'ptoken':([14,20,22,23,32,36,39,42,],[18,18,18,18,18,18,18,18,]),'rules':([14,],[20,]),'expr':([14,20,22,23,32,36,39,42,],[21,21,40,21,40,21,44,40,]),'rule_statments':([5,],[9,]),'rule':([14,20,23,36,],[22,32,42,42,]),'program':([0,],[2,]),'rule_statment':([5,9,],[10,13,]),'operator':([21,40,44,45,],[37,37,37,47,]),'sub_expr':([14,20,21,22,23,32,36,39,40,42,44,],[24,24,33,24,24,24,24,24,33,24,33,]),'options_statment':([3,],[5,]),'empty':([3,14,20,23,36,],[7,26,26,26,26,]),'option_statments':([12,],[17,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> grammar_statment options_statment rule_statments','program',3,'p_program','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',157),
  ('grammar_statment -> GRAMMAR ID SEMI','grammar_statment',3,'p_grammar_statment','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',163),
  ('options_statment -> OPTIONS BLPAREN option_statments BRPAREN','options_statment',4,'p_options_statment','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',169),
  ('options_statment -> empty','options_statment',1,'p_options_statment','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',170),
  ('option_statments -> option_statment','option_statments',1,'p_option_statments','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',176),
  ('option_statments -> option_statments option_statment','option_statments',2,'p_option_statments','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',177),
  ('option_statment -> ID EQUALS ID SEMI','option_statment',4,'p_option_statment','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',183),
  ('rule_statments -> rule_statment','rule_statments',1,'p_rule_statments','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',189),
  ('rule_statments -> rule_statments rule_statment','rule_statments',2,'p_rule_statments','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',190),
  ('rule_statment -> ID COLON rules SEMI','rule_statment',4,'p_rule_statment','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',195),
  ('rules -> rule','rules',1,'p_rules','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',207),
  ('rules -> rules rule','rules',2,'p_rules','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',208),
  ('rule -> expr','rule',1,'p_rule','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',218),
  ('rule -> rule expr','rule',2,'p_rule','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',219),
  ('rule -> rule VERTICAL expr','rule',3,'p_rule','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',220),
  ('rule -> empty','rule',1,'p_rule','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',221),
  ('expr -> ptoken','expr',1,'p_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',233),
  ('expr -> s_expr','expr',1,'p_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',234),
  ('sub_expr -> LPAREN rule RPAREN','sub_expr',3,'p_sub_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',241),
  ('sub_expr -> LPAREN rule RPAREN operator','sub_expr',4,'p_sub_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',242),
  ('s_expr -> <empty>','s_expr',0,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',256),
  ('s_expr -> expr operator','s_expr',2,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',257),
  ('s_expr -> expr','s_expr',1,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',258),
  ('s_expr -> LPAREN RPAREN','s_expr',2,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',259),
  ('s_expr -> expr sub_expr','s_expr',2,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',260),
  ('s_expr -> sub_expr','s_expr',1,'p_s_expr','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',261),
  ('operator -> PLUS','operator',1,'p_operator','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',281),
  ('operator -> MULT','operator',1,'p_operator','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',282),
  ('operator -> QUES','operator',1,'p_operator','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',283),
  ('ptoken -> ID','ptoken',1,'p_ptoken','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',289),
  ('ptoken -> SPE_TOKEN','ptoken',1,'p_ptoken','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',290),
  ('empty -> <empty>','empty',0,'p_empty','/Users/zhaonf/github/breed/tools/java15toply/yacc.py',298),
]
